### ISSUE TITLE
Feature Needed ::: Client closes a connection with the server, could the server eventify it

### ISSUE THREAD

**Issue by aamiryu7** [crussell52/node-socket-ipc#10]
When the client closes or gets abruptly closed, can server eventify this event ? It would be good to have feature.

--Aamir

**Comment by crussell52** [comment]
Would listening to the `close` event on the `net.Socket` work for you?

```js
server.on('connection', (clientId, clientSocket) => {
   clientSocket.on('close', () => {
       console.log(`${clientId} has closed!`);
   });
});
```

**Comment by aamiryu7** [comment]
That's what I was looking for. Let me get a hold of it and revert back to you.

**Comment by aamiryu7** [comment]
That works like a charm. Your the man buddy.

So a little more sugar I wanted to add while asking for both the feature is that i.e. **Feature#9 & Feature#10**, Feature#9 will bring in the ClientInfo with the ClientID being set by the client side as well as other info like **name**, **type**, etc which getting closed eventifying to the server that and then being propogated using another socket to other services that the type service is down, we need to do something about it. That's a background story I wanted to give :-)

**Comment by crussell52** [comment]
Thanks @aamiryu7! It sounds like we can close this issue?

**Comment by aamiryu7** [comment]
Yes, will close it. And to end with a note that other event that we can capture inside this are, so that it may be useful for other people out there looking for a solution based on the event :::

```
clientSocket.on('close', ...);
clientSocket.on('end', ...);
```

Closing it now.
