### ISSUE TITLE
Cleanup bad doc hints for listening to socket events 

### ISSUE THREAD

**Issue by crussell52** [crussell52/node-socket-ipc#11]
Several spots in the docs hint that it may be useful to listen to events on the underlying `net.Socket` events when it is not possible to do so. (Especially in `Server` docs.)

These need to be pruned.

**Comment by aamiryu7** [comment]
Can I do this ?

**Comment by crussell52** [comment]
@aamiryu7 Thanks for the offer to contribute 😄   I've actually already started this one (sorry, should've assigned to myself sooner).

You might want to check out #14 as a good first issue and then if you want to also contribute to the docs, #12 afterwards.

**Comment by crussell52** [comment]
Addressed in f45759e
