### ISSUE TITLE
Server 'closed' event never emitted

### ISSUE THREAD

**Issue by tehnorm** [crussell52/node-socket-ipc#7]
I appreciate you writing this lib - it really fits the bill for our use case for domain socket communication in node.

Had a server hang on me when trying to call `Server.close()` and listening for the `closed` event to confirm shutdown. After some digging it looks like a possible typo:

https://github.com/crussell52/node-socket-ipc/blob/master/src/index.js#L231

Should this emit a `closed` event to match the API docs? Currently a `close` event is being emitted. Good-ole missing one character bugs!

**Comment by crussell52** [comment]
@tehnorm Thanks for the report! Glad the package is useful :) I'm traveling today, but I will check it out as soon as I can.

How would you feel about me generally supporting the `close` event to be more consistent with the norm? I would continue to emit `closed` as well for Client and Server, but effectively deprecate it for removal in 1.0.

**Comment by tehnorm** [comment]
@crussell52, thanks for the quick response! No worries - it is the travel season. For now, I'm just listening to the `close` event. I don't have a strong opinion about event names, other than they match the docs.

**Comment by crussell52** [comment]
Should be fixed in `v0.3.0`, feel free to reopen if the problem persists.

**Comment by tehnorm** [comment]
Thanks @crussell52

**Comment by crussell52** [comment]
@tehnorm no worries. Just heads up. `closed` will now work, but I did deprecate it for removal in v1.0 (unscheduled) in favor of `close` on both `Client` and `Server`
