### ISSUE TITLE
Feature Needed ::: Client can define its type, id & name

### ISSUE THREAD

**Issue by aamiryu7** [crussell52/node-socket-ipc#9]
Hey Russell, good going, I like your library for IPC. Could you please enhance this library with client defining its own Type, ID & name. It would be great to have this feature.

--Aamir

**Comment by crussell52** [comment]
Thanks @aamiryu7!  One of the goals of this project is flexibility without making any assumptions about what exchanges are needed. 

See if this example (using existing functionality) would give you what you want...

Server
```js
const clients = {}
server.on('message.hello', (msg, clientId) => {
  // Record the details in whatever way makes sense for your application.
  clients[clientId] = {
     id: msg.id,
     name: msg.id
     type: msg.type
  }
});
```

Client
```js
client.on('connect', () => {
    client.send('hello', {
      id: 654,
      name: "crussellClient",
      type: "Example"
});
```

**Comment by aamiryu7** [comment]
Thanks for the quick heads up. Let me revert back in sometime.

**Comment by aamiryu7** [comment]
After testing the output of the clients object is as given below :::

```
{
  '1': {
    id: 'a0d7097d-c185-43c4-990d-0017e0cfa1f8',
    name: 'stateServer',
    type: 'client'
  },
  '2': {
    id: 'c564c1b1-259c-4fb1-8034-7ed737aa7d03',
    name: 'apiServer',
    type: 'client'
  },
  '3': {
    id: '72a49945-e5b9-440f-84a0-39c9c6cc30c5',
    name: 'webServer',
    type: 'client'
  }
}
```

what I need is for e.g. :::

```
[
  'a0d7097d-c185-43c4-990d-0017e0cfa1f8': {
    name: 'stateServer',
    type: 'client'
  },
  'c564c1b1-259c-4fb1-8034-7ed737aa7d03': {
    name: 'apiServer',
    type: 'client'
  },
  '72a49945-e5b9-440f-84a0-39c9c6cc30c5': {
    name: 'webServer',
    type: 'client'
  }
]
```

And those **uuids** should be the id's set by the server referencing uuid's given by the client end with the message header.

Let me know if that is possible, that would create a lot of sense in my code structure.
Thanks by the way.

**Comment by aamiryu7** [comment]
By the way, just a thought, why should anyone be caring about the UUID or anything that is set by the Server end, as far as they are getting back the UUID or number that is set by the Server for the Client socket connection. Actually it makes life a bit easy if the ID is set on the Server end for the Client but other optional custom parameters do come in handy while implementing the micro-services architecture.

I was a bit fiddling around with the downloaded code and found that I could do some changes on the Server end (in the **index.js**) if you want. Like telling the server whether to give the ID in a numeric fashion or UUID fashion. That would ease many lives (atleast mine), I'm just guessing here :-).

**Comment by crussell52** [comment]
You are correct that the implementation should not really care about the details of the clientId -- it is really just a way to address messages. 

It may actually be better to think it as a "connection id" because it is changes for every client connection.  So the `webServer` client would have a different id every time it connects.

Are you trying to uniquely identify the client with the `uuid` or are you trying to uniquely identify the connection with the `uuid`?

**Comment by aamiryu7** [comment]
**It may actually be better to think it as a "connection id" because it is changes for every client connection. So the webServer client would have a different id every time it connects.**

-- Yes that does make a sense, since everytime a service (re-)connects to the IPC Server, its connection ID will change.

So, in my architecture, every service is a unique service which will get connected to this Unix Socket Server for sending and receiving to other services via this Socket Service for the purpose of IPC. Hence it is very important to identify the Service name atleast and its type, so when a serviceA needs to send something to serviceB for processing it is accessible via the Socket Server.

Let me know if that makes sense to you.

**Comment by aamiryu7** [comment]
One more thing to add, anyone can very well add the Redis as a Cache Store to remember `connectionID` and its corresponding `serviceName` and `serviceType` to avoid storing it in Node's memory (in-memory).

But in case of a smaller architecture as in our case when its a Unix Socket only based architecture where every `service` is on the same server, it is better to store it in Node's memory to avoid using Redis and its queries to fetch data from it.

By the way, just a question that passed through my mind was, are there any plans to include TCP sockets with or without TLS support ?

**Comment by crussell52** [comment]
@aamiryu7 

With regards to an supporting a config option for "numeric" vs "UUID" ids... I'm reluctant to do so without a strong reason to do so. From your most recent comments, it sounds like you need an id that deterministically identifies the entity acting as a client and the server-generated `clientId` will never meet that need.  Does that sound correct to you?

Regarding TCP, yes I have considered it but I don't have immediate plans nor an immediate need. Feel free to open up a feature request if you have a need for it, though!

**Comment by aamiryu7** [comment]
One of the reason why it came to my mind of using *UUIDs*, is that the integers are quite not common in the JavaScript world when it comes down to things like Mongo, Redis, etc. So I thought of telling you the use-case of making it a UUID based clientIDs if possible. Another thing about numbers or integers is that they have a limit while UUIDs are unique everytime we generate it.

By the way I am using the *uuid* npm module inside the index.js to use UUID instead of integers :-), sorry for the misuse of your library :-(.

Surely will open up a feature request sometime soon. Closing this ticket as well.

**Comment by crussell52** [comment]
>Another thing about numbers or integers is that they have a limit while UUIDs are unique everytime we generate it.

Hmm, looking at the UUID vs numeric use case from this direction has a couple interesting implications...
1. It is _theoretically_ possible to exhaust available ids with a combination of a long-running process and high-connection count. This would take a lot to do since max safe integer is over 9 quadrillion (`9,007,199,254,740,991`)
2. More **practically**, a server restart will start back at `1` which could reduce _traceability_ when it comes to **logging**

Whereas _this_ issue is appropriate closed, I will reference it in a new feature request for changing client id to be a uuid.

Thanks for the thoughts, @aamiryu7!
